ELASTIC:
   HOST: 127.0.0.1
   USER: user
   PASSWORD: password
   PORT: 9200
   SCHEME: http

POSTGRES:
   HOST: 127.0.0.1
   USER: user
   PASSWORD: password
   PORT: 5433
   DB: db

MINIO:
   HOST: 127.0.0.1
   USER: user
   PASSWORD: password
   PORT: 9000

REDIS:
   HOST: 127.0.0.1
   PORT: 6379
